# Generated by Django 5.2.6 on 2025-10-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workout',
            new_name='Exercise',
        ),
    ]
