# Generated by Django 5.2.6 on 2025-10-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_workout_workoutplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exercise_id_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
