# Generated by Django 5.2.6 on 2025-10-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_workout_exercise_id_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='exercise_id_id',
        ),
    ]
