FROM ghcr.io/astral-sh/uv:alpine

RUN apk add --no-cache tzdata

RUN mkdir /app

WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN uv sync

COPY . .

EXPOSE 8000

CMD ["uv", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]
