# Generated by Django 5.2.6 on 2025-10-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.CharField(blank=True, default=' ', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_goals',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_records',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.CharField(blank=True, default=' ', max_length=10),
        ),
    ]
