# Generated by Django 5.2.6 on 2025-10-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_goals',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
